BASESHEET = 'https://docs.google.com/spreadsheets/d/13_LKQoMiY-QWVmdeR9Kn5mXuQ8fTKfWcQ2AEc5spy4A/edit#gid=0'
MASTERDATA_TAIWAN = 'https://docs.google.com/spreadsheets/d/1vQ4nqW5JpX8yIV6twVHGK1l8UFFVNW--isvvxCWNQsQ/edit#gid=0'
MASTERDATA_GLOBAL = 'https://docs.google.com/spreadsheets/d/13TAI7o_WFd71JGlDBh0iCFVkHTeZA8UvTNiNYU0xR6U/edit?hl=zh-tw&gid=0#gid=0'
MASTERDATA_TAIWAN_ALTERNATIVE = 'https://docs.google.com/spreadsheets/d/1Hm-5G8rDBRqr1hY3SKucBRgibZqwIuGejGmhmfQO4xE/edit#gid=0'
MASTERDATA_GLOBAL_ALTERNATIVE = 'https://docs.google.com/spreadsheets/d/1P9wvWrZdNjPSO_vHwElFYPyRdlAtLQXxgZ31FfV0G1s/edit?gid=0#gid=0'